import os
import numpy as np
import pandas as pd

print("--- ADVANCED FEATURE ENGINEERING FOR AIR QUALITY SIGNAL ---")

# Adjust paths to match your setup
processed_dir = "data"
master_output_path = os.path.join(processed_dir, "master_air_quality_dataset.parquet")

# Read existing merged data or raw components (Ensure df has your base columns)
# If loading from existing parquet:
df = pd.read_parquet(master_output_path).sort_values("date").reset_index(drop=True)

# 1. PHYSICAL INTERACTION FEATURES (Ventilation & Stagnation)
# Ventilation Index = Wind Speed * Boundary Layer Proxy (using surface pressure & temp as proxies if BLH absent)
df["ventilation_index"] = df["wind_speed_m_s"] * (df["temp_2m_c"] + 273.15) / (df["surface_pressure_pa"] / 1000.0)

# Stagnation Index: High pressure + Low wind speed ratio
df["stagnation_index"] = (df["surface_pressure_pa"] / 1000.0) / (df["wind_speed_m_s"] + 0.1)

# Wind Vector Components & Momentum
df["wind_u_v_ratio"] = df["wind_u_10m"] / (np.abs(df["wind_v_10m"]) + 1e-5)
df["wind_speed_sq"] = df["wind_speed_m_s"] ** 2

# Thermal & Pressure Gradients (Proxy for inversion layers)
df["temp_pressure_ratio"] = df["temp_2m_c"] / (df["surface_pressure_pa"] / 100000.0)

# 2. EXPONENTIAL MOVING AVERAGES (EMA) & MOMENTUM (Smoothes satellite noise)
for col in ["aod_047_mean", "no2_mean", "wind_speed_m_s", "temp_2m_c", "target_aqi"]:
    if col in df.columns:
        df[f"{col}_ema_3d"] = df[col].ewm(span=3, adjust=False).mean()
        df[f"{col}_ema_7d"] = df[col].ewm(span=7, adjust=False).mean()
        df[f"{col}_rolling_std_7d"] = df[col].rolling(7).std()

# 3. AQI MOMENTUM & RATIOS
df["aqi_momentum_3_7"] = df["target_aqi_ema_3d"] / (df["target_aqi_ema_7d"] + 1e-5)
df["aod_momentum_3_7"] = df["aod_047_mean_ema_3d"] / (df["aod_047_mean_ema_7d"] + 1e-5)

# Drop initial NaNs generated by rolling/lags
df_clean = df.dropna().reset_index(drop=True)

df_clean.to_parquet(master_output_path, engine="pyarrow", index=False)
print(f"SUCCESS: Advanced Feature Set Exported ({len(df_clean)} records, {len(df_clean.columns)} features)")